apply plugin: 'java'

dependencies {
    implementation 'org.jsoup:jsoup:1.18.1'
    compileOnly 'org.apache.httpcomponents.client5:httpclient5:5.3.1'
    compileOnly 'org.apache.httpcomponents.core5:httpcore5:5.3.1'
    compileOnly 'jakarta.persistence:jakarta.persistence-api:3.2.0'
    implementation 'org.json:json:20240303'

    implementation project(':model')
    implementation project(':log')
    implementation project(':util')

    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
}